// apps/react/src/app/Parent.jsx
import React from "react";
import { Child } from './Child';

export class Parent extends React.Component {
  state = {
    myNumberValue: 6
  };

  handleNumberOutput = (newNumberValue) => {
    this.setState({
      myNumberValue: newNumberValue
    });
  }

  render() {
    const hostStyles = {
      border: 'solid 1px navy',
      margin: '5px'
    };

    return (
      <div style={hostStyles}>
        <h2>👩 Parent Component</h2>

        <Child stringInput="This is my string input value" numberInput={this.state.myNumberValue} onNumberOutputChange={this.handleNumberOutput} />
      </div>
    );
  }
}

// apps/angular/src/app/parent.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'mc-parent',
  templateUrl: './parent.component.html',
  styleUrls: ['./parent.component.css']
})
export class ParentComponent implements OnInit {

  constructor() { }

  public myNumberValue = 6;

  ngOnInit() {
  }

  public handleNumberOutput(newNumberValue: number) {
    this.myNumberValue = newNumberValue;
  }

}

<h2>👩 Parent Component</h2>

<mc-child stringInput="This is my string input value" [numberInput]="myNumberValue" (numberOutput)="handleNumberOutput($event)"></mc-child>
