// apps/react/src/app/components/Parent.jsx
import React from "react";
import { Child } from './Child';

export class Parent extends React.Component {
  state = {
    myNumberValue: 6,
    myDateValue: new Date(),
    myArray: []
  };

  handleNumberOutput = (newNumberValue) => {
    this.setState({
      myNumberValue: newNumberValue
    });
  }

  render() {
    const hostStyles = {
      border: 'solid 1px navy',
      margin: '5px'
    };

    return (
      <div style={hostStyles}>
        <h2>👩 Parent Component</h2>

        <Child stringInput="This is my string input value" numberInput={this.state.myNumberValue} onNumberOutputChange={this.handleNumberOutput} />
      </div>
    );
  }
}

// apps/angular/src/app/components/parent.component.ts
import { Component, OnInit, ViewChild, AfterViewInit } from '@angular/core';
import { ChildComponent } from './child.component';

@Component({
  selector: 'mc-parent',
  templateUrl: './parent.component.html',
  styleUrls: ['./parent.component.css']
})
export class ParentComponent {

  constructor() { }

  public myNumberValue = 6;
  public myDateValue = new Date();
  public myArray: string[] = [];

  public handleNumberOutput(newNumberValue: number) {
    this.myNumberValue = newNumberValue;
  }
}

<h2>👩 Parent Component</h2>

<mc-child stringInput="This is my string input value" [numberInput]="myNumberValue" (numberOutput)="handleNumberOutput($event)"></mc-child>

<div *ngIf="myNumberValue > 0">
    Custom Date: {{ myDateValue | customDate }}
</div>

<div *ngFor="let v of myArray; trackBy: getArrayKey">{{v}}</div>
