// apps/angular/src/app/composition/panel/panel/panel.component.ts
import { Component, Input } from '@angular/core';

// panel.component.ts
@Component({
  selector: 'mc-panel',
  templateUrl: './panel.component.html',
  styleUrls: ['./panel.component.css']
})
export class PanelComponent {
  @Input() title: string;
}



<!-- panel.component.html -->
<div class="panel">
  <div class="panel-title">
    {{title}}
  </div>
  <div class="panel-body">
    <ng-content></ng-content>
  </div>
</div>

// apps/react/src/app/composition/Panel/Panel.tsx
import React from 'react';
import './Panel.css';

interface IPanelProps {
  title: string;
}
export class Panel extends React.Component<IPanelProps> {
  render() {
    return (
      <div className="panel">
        <div className="panel-title">
          <h1>{this.props.title}</h1>
        </div>
        <div className="panel-body">
          {this.props.children}
        </div>
      </div>
    );
  }
}
