// apps/angular/src/app/order/order/order.component.ts
// order.component.ts
import { Component, OnInit, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { OrderService } from '../order.service';
import { Order } from '../order.types';

@Component({
  selector: 'mc-order',
  templateUrl: './order.component.html',
  styleUrls: ['./order.component.css']
})
export class OrderComponent implements OnInit, OnChanges, OnDestroy {
  constructor(private _orderService: OrderService) { }

  order: Order;
  ngOnInit(): void {
    this._orderService.getOrder(1)
      .subscribe(o => this.order = o);
  }
  ngOnChanges(changes: SimpleChanges): void {
    // custom update logic
  }
  ngOnDestroy(): void {
    // cleanup logic
  }

  // order.component.ts
  handleEditClicked(lineItemId: number) {
    console.log('Edit was clicked for', lineItemId);
  }

  trackByOrderId(index: number, order: Order) {
    return order.id;
  }
}


<!-- order.component.html -->
<div *ngIf="!order">Loading...</div>
<div *ngIf="order">
  <div>
    Name: {{order.name}}
  </div>
  <div>
    Line Items:
    <div *ngFor="let lineItem of order.lineItems; trackBy:trackByOrderId">
      <!-- order.component.html -->
      <mc-line-item (editClicked)="handleEditClicked($event)"
          [item]="lineItem"></mc-line-item>
    </div>
  </div>
</div>

// apps/react/src/app/Order/Order.jsx
// Order.jsx
import React from 'react';
import { LineItem } from './LineItem';

export class Order extends React.Component {

    componentDidMount() {
        const o = await this.props
            .orderService.getOrder(1);
        this.setState({ order: o });
    }
    componentDidUpdate(prevProps) {
        // custom update logic
    }
    componentWillUnmount() {
        // cleanup logic
    }

    // Order.jsx
    handleEditClick = (id) => {
        console.log('Edit was clicked for', id);
    }

    render() {
        if (!this.order) {
            return (<div>Loading...</div>);
        }

        return (
            <>
                <div>
                    Name: {this.state.order.name}
                </div>
                <div>
                    Line Items:
                    {this.state.order.lineItems.map(lineItem =>
                        // Order.jsx
                        <LineItem onEditClick={this.handleEditClick}
                            item={lineItem} />
                    )}
                </div>
            </>
        );
    }
}
