// apps/react/src/app/composition/Composition.tsx
import * as React from 'react';
import { SimpleCompositionComponent } from './SimpleComposition';
import { InjectedCompositionComponent } from './InjectedComposition';
import { MultipleCompositionComponent } from './MultipleComposition';

const sectionStyles: React.CSSProperties = {
  border: 'solid 1px grey',
  margin: '5px'
};

export default class Composition extends React.Component {
  public render() {
    return (
      <>
        <div style={sectionStyles}>
          <h1>
            Simple:
          </h1>
          <SimpleCompositionComponent>
            <div>Please render this content!</div>
          </SimpleCompositionComponent>
        </div>

        <div style={sectionStyles}>
          <h1>
            Provided Data:
          </h1>
          <InjectedCompositionComponent>
            {
              (count: number) => {
                return (<div>Please render this content with count {count}!</div>);
              }
            }
          </InjectedCompositionComponent>
        </div>

        <div style={sectionStyles}>
          <h1>
            Multiple:
          </h1>
          <MultipleCompositionComponent
            child1={<div>This is the first child</div>}
            child2={(count: number) => <div>This is the second child: {count}</div>}
          />
        </div>
      </>
    );
  }
}

// apps/angular/src/app/composition/main.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'mc-composition',
  templateUrl: './main.component.html',
  styles: [`.bordered { border: solid 1px grey; margin: 5px; }`]
})
export class MainComponent {
  values = [1, 4, 7, 14];
}

<div class="bordered">
  <h1>
    Simple:
  </h1>
  <mc-simple>
    <div>Please render this content!</div>
  </mc-simple>
</div>

<div class="bordered">
  <h1>
    Provided Data:
  </h1>
  <mc-simple>
    <div>
      <div *ngFor="let x of values">Value: {{x}}</div>
    </div>
  </mc-simple>
</div>

<div class="bordered">
  <h1>
    Multiple:
  </h1>
  <mc-multiple>
    <div child1>This is the First Child!</div>

    <div child2>This is the Second Child!</div>
  </mc-multiple>
</div>
