// apps/react/src/app/Order/Address.jsx
import React from 'react';

// Address.jsx
export class Address extends React.PureComponent {
    render() {
        return (
            <div>
                <div>{this.props.street1}</div>
                {this.props.street2
                    && <div>{this.props.street2}</div>
                }
                <div>{this.props.city}, {this.props.state} {this.props.zip}</div>
            </div>
        );
    }
}

export const AddressFC = React.memo((props) => {
    return (
        <div>
            <div>{props.street1}</div>
            {props.street2
                && <div>{props.street2}</div>
            }
            <div>{props.city}, {props.state} {props.zip}</div>
        </div>
    );
})

// apps/angular/src/app/order/address/address.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'mc-address',
  templateUrl: './address.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AddressComponent {
  @Input() street1: string;
  @Input() street2?: string;
  @Input() city: string;
  @Input() state: string;
  @Input() zip: string;
}

<div>
    <div>{{street1}}</div>
    <div *ngIf="street2">{{street2}}</div>
    <div>{{city}}, {{state}} {{zip}}</div>
</div>
